### ISSUE TITLE
[FE03] 서브젝트 오타

### ISSUE THREAD

**Issue by weg901127** [42js/piscine#163]
<img width="682" alt="스크린샷 2021-08-23 오전 12 20 42" src="https://user-images.githubusercontent.com/19397975/130360658-c5eac5fe-a57e-439e-8d7b-a1ddbf47e7b9.png">
03을 너무 완성하고싶었는데 아쉽네요 너무 재미있는 서브젝트였습니다 해당부분 "이슈, 라벨을"이 맞아보이는데 맞나요?

**Comment by hochan222** [comment]
> 03을 너무 완성하고싶었는데 아쉽네요 너무 재미있는 서브젝트였습니다 해당부분 "이슈, 라벨을"이 맞아보이는데 맞나요?

재미있었다니 다행입니다!! 맞습니다. 오타 알려주셔서 감사합니다 ㅎㅎ  좋은 하루 보내세요~!
